export const authCopy = {
  titulo:               "JOHNNY BLAZE",
  subtitulo:            "Sistema de Gestión para Talleres",
  ingresar:             "Ingresar al taller",
  crearCuenta:          "Crear mi cuenta gratis",
  probarGratis:         "Probar gratis",
  ingresarAqui:         "Ingresar aquí",
  olvidasteContra:      "¿Olvidaste tu contraseña?",
  ingresarConTelefono:  "Ingresar con teléfono",
  enviarLinkRecuperacion: "Enviar link de recuperación",
  enviarCodigoSms:      "Enviar código SMS",
  errors: {
    camposVacios:         "Completá los campos",
    contraCorta:          "Mínimo 6 caracteres",
    usuarioNoExiste:      "No encontramos una cuenta con ese correo",
    contraIncorrecta:     "Contraseña incorrecta — revisá y volvé a intentar",
    emailEnUso:           "Ese correo ya tiene una cuenta — ingresá con tu contraseña",
    generico:             "No se pudo iniciar sesión. Revisá tu correo y contraseña.",
    numeroInvalido:       "Número inválido — incluí el código de área sin el 0",
    demasiadosIntentos:   "Demasiados intentos — esperá unos minutos y volvé a intentar",
    smsError:             "No se pudo enviar el código. Verificá el número e intentá de nuevo.",
    codigoIncorrecto:     "Código incorrecto — revisá el SMS y volvé a escribirlo",
    codigoVencido:        "El código venció — pedí uno nuevo",
    otpError:             "No se pudo verificar el código. Intentá de nuevo.",
    ingresaTelefono:      "Ingresá el número completo",
    ingresaCodigo:        "Ingresá el código recibido",
  },
  bloqueo: {
    titulo:           "Tu acceso está suspendido",
    trialVencido:     "Período de prueba vencido",
    suscripcionVencida: "Suscripción vencida",
    datosGuardados:   "Tus datos están guardados y seguros.\nRenovando el acceso los recuperás al instante.",
    elegirPlan:       "Elegí tu plan",
    consultarWA:      "Consultar por WhatsApp",
    cerrarSesion:     "Cerrar sesión",
  },
};
